project:
  type: website

website:
  title: "ATLAS"
  navbar:
    type: dark
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: research-directions.qmd
        text: "Research Directions"
      - href: team.qmd
        text: "The Team"
      - about.qmd

format:
  html:
    theme: lux 
    css: styles.css
    toc: true



