---
title: "Cyber, Physical, and Social (CPS) Security for Infrastructure Systems"
---

Energy and water crises appeal for a paradigm shift to autonomous operation and control of interconnected water and energy systems for improved recycling of water and energy through conversions between different forms (e.g., electricity, heat) and reuse. Such autonomy brings challenges of protecting highly dynamic water-energy infrastructure systems involving cyber, physical, and social components. For example, water and energy conversion and recycling can exist between connected drinking water treatment systems, wastewater recycling and stormwater management systems, power grids, and emerging nuclear-renewable energy systems. Coordinated control of water-energy conversion and recycling processes are necessary for meeting the changing demands for different types of water (e.g., drinking, medical use) and energy (e.g., heat, electricity) with water/energy production units having uncertainties. A typical example is the control of an emerging nuclear-renewable hybrid energy system that uses a nuclear plant, a thermal power cycle, and a wind power plant to produce hydrogen, heat, and electricity with reduced carbon emissions while satisfying diverse forms of energy needs. Even experienced and skillful operators could hardly ensure the safety and efficiency of continuously monitoring and coordinating the high-dimensional systems dynamics of water-energy synergies. 

Autonomous control and operation techniques augmented by machine learning methods are under development for achieving adaptive control of such synergies. Unfortunately, such systems usually need to collect large amounts of data that capture the operation histories of various water-energy systems, including systems sensor logs, human control behaviors, and reactions of water-energy users. Sharing and using such historical data for machine learning of control strategies could bring risks of data leakages, cyber attacks that mislead the control algorithms, and physical attacks that leverage the knowledge derived from leaked data. All these threats in cyber and physical spaces can cause water quality problems, energy delivery disruptions, and other events that influence society and communities.

ATLAS researchers have been exploring research questions related to cyber-physical security of water-energy synergy systems and new techniques for proactive protection of data and models used for water-energy system operations. One major branch is to develop data collection techniques that can protect the operational data and privacy associated with the behavioral data used for training the adaptive control strategies. One example project is the “Privacy Preserving Computational Cameras” that allow flexible filtering of video information for protecting privacy of operators and infrastructure service users (e.g., building occupants). Another branch is the development of novel machine learning models that can protect the raw data used for machine learning. An example is the development and validation of new federated learning algorithms for learning control strategies from distributed sensor networks and mobile devices while protecting the raw data. A number of projects also provide systems operation data for carrying out vulnerability analysis and predictive protection against attacks based on the identified vulnerabilities of operation processes.

## Associated Projects

### Privacy-preserving Computational Cameras

### Energy Efficient Connected Community of Buildings
