---
title: "Research Directions"
---

## Responsible Virtual Power Plants

Central to our ability to avoid a climate crisis through decarbonization is a radical shift in the operation of the electrical power system to allow for the integration of clean energy sources that are less predictable, reliable and not continuously available (e.g., wind, solar). Due to the nature of power systems and the practicalities of storing electricity, the grid is operated to maintain a careful and continuous balance between demand and supply at all times. Thus, increased renewables in the grid will require us to move away from centralized scheduling and control of large predictable carbon intensive generation resources (e.g., gas and coal power plants) and towards decentralized coordination of a multitude of demand-side resources that can better accommodate the increased amount of intermittent and variable generation resources that are being introduced into the grid. In other words, solving our climate crisis requires that we completely change the way we operate buildings, allowing them to become a reliable asset for grid operations.

The US Department of Energy (DOE) estimates that unlocking this resource could result in national benefits exceeding US$18 billion a year by 2030, and a reduction in Green House Gas emissions of over XX%. However, to achieve this, individual participants (e.g., single domestic loads with flexibility potential such as domestic water heaters, or small photovoltaic systems) need to be aggregated through coordination in order for them to be able to provide meaningful services in the same way that traditional power plants did before. Because of the timescales at which these decisions are made, most of the decisions are done autonomously with little to no human interaction (e.g., if there is excess wind capacity at some point in time, a network of electric water heaters can store this excess electricity by increasing water temperature by a few degrees without needing to coordinate this action with the end users). This shift is already underway and there are a number of companies, sometimes referring to themselves as virtual power plants, providing services to the grid (anywhere from peak shaving to frequency regulation) by coordinating the usage of large collections of customers who they contract with. Autonomous technologies, such as smart thermostats, smart chargers for electric vehicle batteries, smart and connected heat pumps and other products are paving the road towards this vision.

As this shift towards more responsive demand and more grid-enabled buildings continues, it is important to ask ourselves if and how these autonomous technologies are taking into consideration the values of the communities that they serve when making decisions on their behalf. To start, as decision-making moves from centralized resources to distributed ones, it is important to respect end-user privacy. Similarly, security and safety concerns become more pertinent when the control of loads is passed on to the hands of algorithms (both because they can be abused by malicious actors, but also because it may lead to unintended consequences). Less evident but just as important are equity and justice considerations in this space. Without properly aligning the incentives for these contracts between aggregators and resource owners, there is the risk of ignoring the impacts and opportunities for large portions of the community. As an example, if only homeowners with smart thermostats can participate in this market, we may be distributing the rewards unevenly across the community when we could have used excess capacity to cool low-income homes that are more sensitive to energy costs.

## Federated, Community-Owned/Authored Models of Infrastructure Assets

To be able to support autonomous technologies/infrastructure systems/communities, there is a need to have a digital twin of them.  Such digital twin can contain not just information about physical assets, but also about their usages (the context under which such systems get used)  as well as community preferences.  As it is expected that several things will be uncertain, the digital twin will also include uncertainty modeling to support not only identification of current operational improvements, but also projection to the future to enable predictive capabilities and prognosis.  Hence, such a digital twin will serve as the core repository of information about the autonomous infrastructure systems.

While there are many digital twin efforts in many domains, depending on the domain, the modeling paradigm and what is referred to as digital twin is different.  It is also not clear how privacy and equity concerns are embedded in the current digital twin modeling efforts.  

It is expected that it would be impossible to have a single digital twin to support a variety of usages and context.  Hence, there is a need for federated digital twins.  Such federated architecture would also allow privacy preservation and equity ensurance while supporting a variety of decision-making.  It is also important to develop bias-free or bias-aware preprocessing and data fusion techniques to enable responsible autonomy while supporting transparency and trust.


## Cyber, Physical, and Social (CPS) Security for Infrastructure Systems

Energy and water crises appeal for a paradigm shift to autonomous operation and control of interconnected water and energy systems for improved recycling of water and energy through conversions between different forms (e.g., electricity, heat) and reuse. Such autonomy brings challenges of protecting highly dynamic water-energy infrastructure systems involving cyber, physical, and social components. For example, water and energy conversion and recycling can exist between connected drinking water treatment systems, wastewater recycling and stormwater management systems, power grids, and emerging nuclear-renewable energy systems. Coordinated control of water-energy conversion and recycling processes are necessary for meeting the changing demands for different types of water (e.g., drinking, medical use) and energy (e.g., heat, electricity) with water/energy production units having uncertainties. A typical example is the control of an emerging nuclear-renewable hybrid energy system that uses a nuclear plant, a thermal power cycle, and a wind power plant to produce hydrogen, heat, and electricity with reduced carbon emissions while satisfying diverse forms of energy needs. Even experienced and skillful operators could hardly ensure the safety and efficiency of continuously monitoring and coordinating the high-dimensional systems dynamics of water-energy synergies. 

Autonomous control and operation techniques augmented by machine learning methods are under development for achieving adaptive control of such synergies. Unfortunately, such systems usually need to collect large amounts of data that capture the operation histories of various water-energy systems, including systems sensor logs, human control behaviors, and reactions of water-energy users. Sharing and using such historical data for machine learning of control strategies could bring risks of data leakages, cyber attacks that mislead the control algorithms, and physical attacks that leverage the knowledge derived from leaked data. All these threats in cyber and physical spaces can cause water quality problems, energy delivery disruptions, and other events that influence society and communities.

ATLAS researchers have been exploring research questions related to cyber-physical security of water-energy synergy systems and new techniques for proactive protection of data and models used for water-energy system operations. One major branch is to develop data collection techniques that can protect the operational data and privacy associated with the behavioral data used for training the adaptive control strategies. One example project is the “Privacy Preserving Computational Cameras” that allow flexible filtering of video information for protecting privacy of operators and infrastructure service users (e.g., building occupants). Another branch is the development of novel machine learning models that can protect the raw data used for machine learning. An example is the development and validation of new federated learning algorithms for learning control strategies from distributed sensor networks and mobile devices while protecting the raw data. A number of projects also provide systems operation data for carrying out vulnerability analysis and predictive protection against attacks based on the identified vulnerabilities of operation processes.

